import { address, lamports, type EncodedAccount } from "@solana/kit";
import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import {
  EscrowKeys,
  deriveSharedSeed,
  verifyConfidentialFunding,
} from "../../confidential";

test("shared keys, openings and amount ciphertexts match the Rust vectors", async () => {
  const vectors = JSON.parse(
    readFileSync("clients/test-vectors/confidential-amount-b.json", "utf8"),
  );
  const seed = await deriveSharedSeed(address(vectors.swap_pda), (message) =>
    createHmac("sha256", Buffer.from(vectors.master_key, "hex"))
      .update(message)
      .digest(),
  );
  assert.equal(Buffer.from(seed).toString("hex"), vectors.shared_seed);
  const keys = EscrowKeys.fromSeed(seed),
    pubkey = keys.elgamal.pubkey(),
    secret = keys.elgamal.secret();
  try {
    for (const [actual, expected] of [
      [pubkey.toBytes(), vectors.elgamal_public_key],
      [secret.toBytes(), vectors.elgamal_secret_key],
      [keys.ae.toBytes(), vectors.ae_key],
      [keys.openingLo.toBytes(), vectors.opening_lo],
      [keys.openingHi.toBytes(), vectors.opening_hi],
    ] as const)
      assert.equal(Buffer.from(actual).toString("hex"), expected);
    for (const vector of vectors.amounts) {
      const cipher = keys.encryptAmount(BigInt(vector.amount));
      assert.equal(
        Buffer.from(cipher.lo).toString("hex"),
        vector.ciphertext_lo,
      );
      assert.equal(
        Buffer.from(cipher.hi).toString("hex"),
        vector.ciphertext_hi,
      );
    }
  } finally {
    pubkey.free();
    secret.free();
    keys.free();
  }
});

test("a Rust-created swap and escrow verify with a TypeScript-derived seed", async () => {
  // Regenerated by the ignored Rust test write_confidential_funding_vector.
  const vector = JSON.parse(
    readFileSync("clients/test-vectors/confidential-funding.json", "utf8"),
  );
  const account = (raw: {
    address: string;
    owner: string;
    lamports: string;
    data: string;
  }): EncodedAccount => {
    const data = new Uint8Array(Buffer.from(raw.data, "hex"));
    return {
      address: address(raw.address),
      programAddress: address(raw.owner),
      lamports: lamports(BigInt(raw.lamports)),
      executable: false,
      space: BigInt(data.length),
      data,
    };
  };
  const swap = account(vector.swap),
    escrow = account(vector.escrow_b);
  assert.equal(swap.data.length, 586);
  const seed = await deriveSharedSeed(swap.address, (message) =>
    createHmac("sha256", Buffer.from(vector.master_key, "hex"))
      .update(message)
      .digest(),
  );
  const keys = EscrowKeys.fromSeed(seed),
    amount = BigInt(vector.amount_b);
  try {
    // Decodes the 586-byte tail and checks PDA, escrow key, ciphertexts and AE.
    await verifyConfidentialFunding(swap, escrow, keys, amount);
    await assert.rejects(
      verifyConfidentialFunding(swap, escrow, keys, amount + 1n),
      { name: "ConfidentialError", code: "AmountMismatch" },
    );
  } finally {
    keys.free();
  }
});
